### ISSUE TITLE
Testing Katia.

### ISSUE THREAD

**Issue by Obadha** [ianjuma/katia#1]
I forked the project and cloned the repository locally. I run runserver.py and I get the message "Awesome running at - 8000 " which I assume means everything runs as it should.
What's the number to call? How do I however get to test the katia application itself? i.e place calls and have them go through, or place call and get to hear back a voice message.
Is this the code that does that if not, is that elsewhere?
Please help.

**Comment by ianjuma** [comment]
that's all the code - now, you can request for a voice number and keyword that you can map on your Africastalking account and test with.

Request for a number from info [at] africastalking com, and a keyword too

**Comment by Obadha** [comment]
I see.
I'll see if I can get my hands on those, then.

Thanks!
